######################################################################
# Automatically generated by qmake (2.01a) mer. avr. 27 19:55:05 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h strokedrawer.h stroketraining.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp strokedrawer.cpp stroketraining.cpp
